from __future__ import annotations
from pathlib import Path
import json
from typing import Any

SEV_TO_LEVEL = {"low": "note", "medium": "warning", "high": "error", "critical": "error"}
STATUS_TO_SUPPRESS = {"pass"}

def _build_rules_index(findings: list[dict]) -> list[dict]:
    seen = set()
    rules = []
    for f in findings:
        rid = f.get("rule_id", "unknown.rule")
        if rid in seen:
            continue
        seen.add(rid)
        rules.append({
            "id": rid,
            "name": rid,
            "shortDescription": {"text": rid},
            "fullDescription": {"text": "AIGOV policy rule"},
            "help": {"text": "Generated by aigov-scan policy engine."}
        })
    return rules

def _pick_location_uri(target_root: str, evidence: list[dict], rule_id: str) -> str:
    if "license" in rule_id:
        for ev in evidence:
            if ev.get("kind") == "license":
                paths = ev.get("payload", {}).get("paths_scanned") or []
                if paths:
                    return str(Path(target_root) / paths[0])
    return target_root

def write_sarif(path: Path,
               findings: list[dict],
               evidence: list[dict],
               target_root: str,
               tool_version: str,
               information_uri: str) -> None:
    rules = _build_rules_index(findings)

    results: list[dict[str, Any]] = []
    for f in findings:
        if f.get("status", "pass") in STATUS_TO_SUPPRESS:
            continue
        sev = f.get("severity", "low")
        rid = f.get("rule_id", "unknown.rule")
        uri = _pick_location_uri(target_root, evidence, rid)
        results.append({
            "ruleId": rid,
            "level": SEV_TO_LEVEL.get(sev, "warning"),
            "message": {"text": f.get("message", rid)},
            "locations": [{"physicalLocation": {"artifactLocation": {"uri": uri}}}]
        })

    sarif = {
        "version": "2.1.0",
        "$schema": "https://json.schemastore.org/sarif-2.1.0.json",
        "runs": [{
            "tool": {"driver": {"name": "aigov-scan", "informationUri": information_uri, "version": tool_version, "rules": rules}},
            "results": results
        }]
    }
    path.write_text(json.dumps(sarif, indent=2), encoding="utf-8")
